# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.DurationInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.DurationInput.setObjectName("DurationInput")
        self.gridLayout_7.addWidget(self.DurationInput, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 3, 1, 1)
        self.PositionInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.PositionInput.setObjectName("PositionInput")
        self.gridLayout_8.addWidget(self.PositionInput, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 0, 4, 1, 1)
        self.TurnsInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.TurnsInput.setObjectName("TurnsInput")
        self.gridLayout_8.addWidget(self.TurnsInput, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 2, 1, 1)
        self.Current = QtWidgets.QLabel(self.groupBox_5)
        self.Current.setObjectName("Current")
        self.gridLayout_2.addWidget(self.Current, 4, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.velocityInput = QtWidgets.QLineEdit(self.groupBox_4)
        self.velocityInput.setObjectName("velocityInput")
        self.gridLayout_6.addWidget(self.velocityInput, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.CCWRadio = QtWidgets.QRadioButton(self.groupBox_6)
        self.CCWRadio.setObjectName("CCWRadio")
        self.gridLayout_16.addWidget(self.CCWRadio, 0, 1, 1, 1)
        self.CWRadio = QtWidgets.QRadioButton(self.groupBox_6)
        self.CWRadio.setObjectName("CWRadio")
        self.gridLayout_16.addWidget(self.CWRadio, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MoveToPosition = QtWidgets.QRadioButton(self.groupBox_7)
        self.MoveToPosition.setObjectName("MoveToPosition")
        self.gridLayout.addWidget(self.MoveToPosition, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_7)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 3, 1, 1)
        self.MoveForDuration = QtWidgets.QRadioButton(self.groupBox_7)
        self.MoveForDuration.setObjectName("MoveForDuration")
        self.gridLayout.addWidget(self.MoveForDuration, 1, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_7)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 1, 1, 1)
        self.MoveNRounds = QtWidgets.QRadioButton(self.groupBox_7)
        self.MoveNRounds.setObjectName("MoveNRounds")
        self.gridLayout.addWidget(self.MoveNRounds, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.line_3 = QtWidgets.QFrame(self.groupBox_8)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_17.addWidget(self.line_3, 0, 2, 1, 1)
        self.ManualCW = QtWidgets.QPushButton(self.groupBox_8)
        self.ManualCW.setObjectName("ManualCW")
        self.gridLayout_17.addWidget(self.ManualCW, 0, 5, 1, 1)
        self.ManualCCW = QtWidgets.QPushButton(self.groupBox_8)
        self.ManualCCW.setObjectName("ManualCCW")
        self.gridLayout_17.addWidget(self.ManualCCW, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setObjectName("label_11")
        self.gridLayout_17.addWidget(self.label_11, 0, 3, 1, 1)
        self.StartBtn = QtWidgets.QPushButton(self.groupBox_8)
        self.StartBtn.setObjectName("StartBtn")
        self.gridLayout_17.addWidget(self.StartBtn, 0, 0, 1, 1)
        self.StopBtn = QtWidgets.QPushButton(self.groupBox_8)
        self.StopBtn.setObjectName("StopBtn")
        self.gridLayout_17.addWidget(self.StopBtn, 0, 1, 1, 1)
        self.gridLayout_17.setColumnStretch(0, 1)
        self.gridLayout_17.setColumnStretch(1, 1)
        self.gridLayout_17.setColumnStretch(4, 1)
        self.gridLayout_17.setColumnStretch(5, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Velocity Control"))
        self.label_4.setText(_translate("MainWindow", "Duration"))
        self.label_7.setText(_translate("MainWindow", "sec"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Position Control"))
        self.label_2.setText(_translate("MainWindow", "Position"))
        self.label_6.setText(_translate("MainWindow", "inc"))
        self.label_3.setText(_translate("MainWindow", "No. of turns"))
        self.label_8.setText(_translate("MainWindow", "Current"))
        self.label_9.setText(_translate("MainWindow", "mA"))
        self.Current.setText(_translate("MainWindow", "current current!"))
        self.label_5.setText(_translate("MainWindow", "rpm"))
        self.label.setText(_translate("MainWindow", "Velocity  "))
        self.groupBox_6.setTitle(_translate("MainWindow", "Moving Direction"))
        self.CCWRadio.setText(_translate("MainWindow", "Counterclockwise"))
        self.CWRadio.setText(_translate("MainWindow", "Clockwise"))
        self.MoveToPosition.setText(_translate("MainWindow", "Move to Position"))
        self.MoveForDuration.setText(_translate("MainWindow", "Move for Duration"))
        self.MoveNRounds.setText(_translate("MainWindow", "Move N Rounds"))
        self.ManualCW.setText(_translate("MainWindow", "Rotate CW"))
        self.ManualCCW.setText(_translate("MainWindow", "Rotate CCW"))
        self.label_11.setText(_translate("MainWindow", "Manual:"))
        self.StartBtn.setText(_translate("MainWindow", "Start"))
        self.StopBtn.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
